### ISSUE TITLE
Get Extension API working with TYPO3 CMS >= 6.2

### ISSUE THREAD

**Issue by opi99** [TYPO3-coreapi/ext-coreapi#46]
Following functions do not work with TYPO3 CMS >= 6.2
- [x] #63 Make extensionapi:updatelist working with TYPO3 CMS >= 6.2
- [x] #64 Make extensionapi:install working with TYPO3 CMS >= 6.2
- [x] #65 Make extensionapi:uninstall working with TYPO3 CMS >= 6.2
- [x] #66 Make extensionapi:configure working with TYPO3 CMS >= 6.2
- [ ] #67 Make extensionapi:fetch working with TYPO3 CMS >= 6.2
